liftbridge-io/liftbridge

- README.md
- documentation/configuration.md
- server/commitlog/commitlog.go
- server/commitlog/delete_cleaner.go
- server/commitlog/delete_cleaner_test.go
- server/config.go
- server/server_test.go
- server/stream.go
Support log retention by the number of messages.
> Implement retention.max.messages

- .circleci/config.yml
- Dockerfile
> Add Dockerfile

- .circleci/config.yml
- Dockerfile
- README.md
- documentation/configuration.md
- documentation/quick_start.md
- main.go
- main_test.go
- server/config.go
The --nats-server value is not being read.
> Handle --nats-server on cli correctly

- server/commitlog/index.go
Expand the index file and re-mmap if it's full before writing.
Fixes #18.
> Fix index write panic

- server/signal_windows.go
Fix issue as pointed out by #43.
> Fix windows build

- documentation/configuration.md
- server/commitlog/commitlog.go
- server/commitlog/compact_cleaner.go
- server/commitlog/compact_cleaner_test.go
- server/config.go
- server/stream.go
Parallelize the key-offset scanning portion of log compaction.
> Parallelize log compaction

- server/api.go
- server/commitlog.go
- server/commitlog/commitlog.go
- server/commitlog/commitlog_test.go
- server/commitlog/compact_cleaner_test.go
- server/commitlog/segment.go
- server/commitlog/util_test.go
Remove TODOs and commit to using int64 for offsets.
> Clean up firstOffset/lastOffset logic

- server/raft.go
- server/replicator.go
- server/server.go
- server/stream.go
This is a newer feature in the NATS client that simplifies response
code.
> Use Msg.Respond to reply to NATS requests

- .circleci/config.yml
- Dockerfile
> Fix dockerfile

- server/conf/lex.go
- server/conf/parse.go
- server/metadata.go
* Fix typo.
* Simplify of expression.
> Some code improvements

- documentation/README.md
- documentation/client.md
Add documentation with guidance for implementing client libraries.
> Client documentation

- documentation/configuration.md
- server/config.go
- server/config_test.go
- server/configs/nats_auth.conf
Fix #108 by adding user and password options to NATS section in config
file.
> Add user/password config for NATS

- server/commitlog/commitlog.go
- server/commitlog/commitlog_test.go
- server/commitlog/segment.go
- server/commitlog/segment_test.go
- server/commitlog/util_test.go
- server/config.go
While interacting with the codebase I noticed a couple of linters perking up and suggesting a couple things. Maybe you'd like to pull these in?
> Linter fixes

- server/server_test.go
> Add unit test around metadata leadership lifecycle

- documentation/deployment.md
- documentation/quick_start.md
> Include liftbridge-docker in documentation

- documentation/configuration.md
Describe the difference between listen and host/port configuration.
> Add more detail to listen and host/port docs

- server/commitlog/commitlog_test.go
- server/commitlog/message.go
> Handle messages with nil values

- documentation/overview.md
> Fix typo in overview.md

- docker/dev-standalone/README.md
- documentation/deployment.md
- documentation/quick_start.md
> Update docker documentation

- .circleci/config.yml
- website/deploy/Makefile
> Automate website deploys

- documentation/faq.md
- documentation/feature_comparison.md
- documentation/overview.md
- website/i18n/en.json
- website/sidebars.json
Also update overview and faq docs.
> Add feature comparison matrix

- server/api_test.go
- server/server_test.go
> Fix flaky test

- Dockerfile
- k8s/Dockerfile.k8s
> Remove bzr from Dockerfiles

- documentation/roadmap.md
- website/i18n/en.json
- website/sidebars.json
> Document product roadmap

- documentation/client_implementation.md
Updates around changes to the publish API.
> Update client implementation guidance

- documentation/roadmap.md
Mark Automatic Partition Pausing as complete.
> Update product roadmap [skip ci]

- server/commitlog/delete_cleaner.go
- server/commitlog/delete_cleaner_test.go
Fix bug where index out of range panic happens due to a logic error
around message retention rules.
> Fix message retention bug

- go.mod
- go.sum
- server/metadata.go
> Metadata pause status

- server/api.go
First minimal pass at implementing stop offset logic (#280). Looks like most of the code is already there, assuming that `ResourceExhausted` is an acceptable status code.
By default `stopOffset` will be -1, which means "wait for new messages". If the partition is read-only then `stopOffset` is set to the newest offset of the partition. In future `stopOffset` can be set using a function similar to the existing `getStartOffset()`
> Implement stop offset logic

- server/api.go
Attempt to wait for remaining acks for any in-flight messages before
ending PublishAsync sessions.
> Drain acks when client closes PublishAsync RPC

- server/api_test.go
- server/metadata.go
Fix an edge case when deleting a stream directory that has been
partially removed.
Fixes #297
> Fix delete stream error when dir is not empty

- server/commitlog/index.go
Fix a leak where mmapped files are not unmapped when segments are
closed.
Fixes #302
> Unmap memory mapped indexes on close

- server/api_test.go
- server/fsm.go
- server/metadata.go
- server/replicator_test.go
- server/server_test.go
- server/stream.go
Account for partition leadership changes and pausing/resuming.
> Correctly compute broker partition load

- server/api.go
- server/api_test.go
> Validate NATS subject in CreateStream

- server/replicator.go
Replication loop contains `defer` inside endless loop, leading to leak WithCancel context every loop turn.
`defer` should be wrapped inside anonymous function call to limit a visibility.
> Fix memory leak in replication loop

- documentation/authentication_authorization.md
Add documentation to explain TLS authentication behavior.
Support https://github.com/liftbridge-io/liftbridge/issues/36
> Add docs to briefly explain authenticaion

- documentation/authentication_authorization.md
- website/i18n/en.json
- website/package-lock.json
- website/sidebars.json
- website/yarn.lock
Also make some minor tweaks to the authentication and authorization
docs.
> Add authentication docs to menu [skip ci]

- server/metadata.go
- server/partition.go
- server/replicator_test.go
- server/server_test.go
Fixes a bug where failed stream partition leaders are not properly
reported and failed over.
> Fix partition leader failover
