server/replicator_test.go, server/stream.go
When shrinking the ISR, insert a check to commit messages since messages
might now be eligible for committing.
=> Commit messages on ISR shrink

server/config.go
=> Pass NATS config pointer to parseNATSConfig so original is updated

README.md, documentation/configuration.md, main.go, server/config.go, server/metadata.go, server/raft.go, server/server_test.go, server/stream.go, server/stream_test.go
This allows configuring a minimum ISR size which prevents messages from
being committed if the ISR drops below this size.
=> Implement min.insync.replicas

server/commitlog/segment.go, server/stream.go
Ensure the Segment is not marked as closed after being replaced.
=> Segment replace fix

server/commitlog/index.go, server/commitlog/index_test.go
I ran into an index out of range panic in `Index.ReadAt` while experimenting with liftbridge. (Really cool project, thanks for creating it!)
Found that the index is not expanded in `Index.writeAt` when `position < size && position + len(p) > size`. In this case not all the entries are written to the index but `position` is updated as though they had been, resulting in `position > size`.
Also added a couple test for the initial size before realizing the `Index.InitializePosition` handles updating the position to the correct point on creation. I left them in since they could be useful, but can remove them if you'd like.
Thanks again!
=> commitlog: ensure index has enough room for all entries on expansion

go.mod, go.sum, server/api_test.go, server/replicator_test.go, server/server_test.go, vendor/github.com/liftbridge-io/go-liftbridge/client.go, vendor/modules.txt
Replace low-level NATS publishes with the new Liftbridge Publish API.
=> Use Publish API in tests

documentation/configuration.md, server/commitlog/commitlog.go, server/commitlog/delete_cleaner_test.go, server/common_test.go, server/config.go, server/fsm.go, server/logger/logger.go, server/server.go, server/server_test.go
Also add new config option `log.recovery` to allow enabling logs during
Raft recovery.
=> Suppress logs during Raft recovery by default

go.mod, go.sum, server/api_test.go, server/metadata.go, server/server_test.go
Fail fast if there is no known metadata leader when propagating metadata
requests such as CreateStream.
=> Fail fast on metadata request propagate

Dockerfile
Updated the Dockerfile to use golang modules. Also, added Bazar to the first stage of the build, because one package depends on it. These changes should fix #83.
=> Enable golang modules for Docker build.

Dockerfile
As pointed out in [his](https://github.com/liftbridge-io/liftbridge/pull/84#discussion_r307193292) comment by @annismckenzie, calling `go get` is not needed. Sorry for opening new PR for this same issue again, I meant to update the Dockerfile yesterday but I had to finish  early.
=> Removing unnecessary `go get`

documentation/configuration.md, main.go, server/config.go, server/server.go
This PR adds client authentication via TLS certificate. The Liftbridge server can enforce client authentication using the tls.client.auth configuration entry or command line parameter. The CA certificate to use when authenticating clients can also be specified.
No unit tests have been written because none existed regarding TLS. Can add some if needed. What are your thoughts about that @tylertreat?
=> Added client authentication via certificate

documentation/deployment.md, documentation/quick_start.md, website/deploy/app.yaml
Also redirect /docs to the documentation and some other general doc
cleanup.
=> Add clustering section to quick start guide

server/api.go
Ensure that empty strings cannot be passed as stream name or subject on
CreateStream.
Fixes #140.
=> Validate CreateStream arguments

Makefile, docker/dev-standalone/Dockerfile
Needed to be statically linked to work when copied to the docker image. Current image is toutputting "liftbridge: Not found" and exiting.
=> Fix liftbridge dev compilation

server/api_test.go, server/metadata.go, server/replicator_test.go
Use the context deadline on CreateStream to wait for a metadata leader
to be established during CreateStream propagation.
This fixes #163.
=> Fix no metadata leader race

server/api_test.go, server/metadata.go
Fix a race condition edge case on RPC propagation where an RPC is made
when there is no metadata leader. If the server receiving the RPC
becomes leader, it may propagate the request to itself before the
propagation NATS subscription has been established. In this case, the
propagated RPC is missed and the original RPC times out.
To fix this, we check if the server receiving the RPC has become the
metadata leader. If it has, there is no need to propagate the request as
it can be performed locally.
=> Fix RPC propagation race edge case

documentation/configuration.md, server/config.go
For example with a config.yml of:
```yml
host: localhost
```
One can override the advertised host with:
```sh
env LIFTBRIDGE_HOST=liftbridge-0.liftbridge-headless \
liftbridge --raft-bootstrap-seed --config config.yml
```
I stumbled upon this trying to run the standalone-dev container inside
docker-compose where I was using the virtual network hostnames to wire
everything together. Which lead me to these issues:
https://github.com/liftbridge-io/go-liftbridge/issues/33
https://github.com/liftbridge-io/liftbridge/issues/138
The initial connection was fine but the advertised host in the metadata
returned from liftbridge was `127.0.0.1` so when the go-liftbridge
client further went to connect to the "brokers" it would fail.
I'm pretty sure people would struggle to get this working with …
=> Allow overriding viper config with env vars

docker/dev-standalone/Dockerfile
bzr is no longer available in Alpine Linux as of 3.12
(https://github.com/alpinelinux/docker-alpine/issues/87).
=> Fix dev-standalone build

server/replicator.go
Fix a race condition around registering data waiters during replication
when a replica has caught up with the leader. This involved sending the
notification to the replica before unregistering the waiter, which could
cause a subsequent request from the replica from being unable to
register a new waiter since the previous one had not yet been removed.
This race would result in extremely high tail latencies on message
commits.
To fix this, we simply unregister the waiter before sending the
notification to the replica.
=> Fix data waiter race in replication causing high tail latencies

server/api.go, server/metadata.go, server/raft.go, server/server.go
This fixes a nil pointer which caused the server to panic in the event of an async error on a NATS connection.
Also remove all uses of non-scoped NATS subjects, e.g. _INBOX.* and nuids. There were a couple cases where subjects were not being scoped, namely publish acks and some internal metadata subjects. This makes it easier for users who have authorization rules around subjects configured on NATS.
=> Fix NATS async error panic and scope all internal subjects to namespace

server/partition.go
Check if the replication request loop was stopped after a replication
error in order to avoid spurious leader reports. This is mainly to
handle the case of a leader failover causing additional error logs which
are benign but can be confusing.
=> Preempt replication request loop earlier

server/partition.go, server/replicator_test.go, server/server_test.go
Ensure if a partition ISR changes and the partition is paused and
subsequently resumed that the ISR matches the state when the partition
was paused.
This fixes #236.
=> Maintain ISR across partition pauses

k8s/entrypoint.sh
Make sure HOSTNAME is different for each running pod, for proper advisory of stream metadata
=> Incorrect hostname used for stream metadata

server/metadata.go
This adds a `paused` field to every partition's metadata, representing the partition's paused status.
=> Add paused status to partition metadata

go.mod, go.sum, server/api.go, server/server_test.go
Liftbridge offers the option of pausing a stream (with some or all of its partitions) to reduce the amount of CPU and memory usage on idle streams. When that happens, every subscriber to a partition receives an error. Publishing to a paused partition will resume it, allowing it to function as before.
Our use-case includes a situation where we would like to read from a partition even if it is paused. It has to be resumed to do so, but we do not want to publish to it. This PR adds an option to the subscription request to allow it to resume a partition instead of returning an error.
=> Add an option to allow resuming a paused partition when subscribing

.circleci/config.yml, Dockerfile, k8s/Dockerfile.k8s
We briefly discussed this on the community slack a couple weeks ago, let me know what you think :) 
Not sure if you'd rather have the k8s image pushed to a different repo instead of a tag suffix.
=> Docker image as non root and push k8s image to dockerhub

server/commitlog/reader.go, server/commitlog/reader_test.go
Fix a bug where retention limits are applied to a log past a HW. This
caused subscribe calls to return an "entry not found" error.
This fixes #28.
=> Fix bug related to HW and empty log

server/server.go
This PR adds an exported function to access the server's listen port. This is useful for unit tests where you would want to use an OS assigned port instead of an hardcoded one to prevent any clashes. In that case you need to have a way to find out what port has been assigned.
=> Expose server listen port

server/metadata.go, server/server.go
Liftbridge allows setting 0 as a listen port. In that case the operating system will provide a free port to listen to. This prevents any port conflict between processes and/or during testing.
Liftbridge also uses a connection port that is sent to clients. Configuring it to listen on port 0 means that the clients will also receive 0 as a port to connect to, which will fail.
This PR fixes this issue by making the server send the port it is currently listening to in case the configured connection port is 0.
=> Allow using an automatically assigned connection port

docker/dev-standalone/Dockerfile, docker/dev-standalone/README.md
Hey,
Noticed that the dev-standalone Dockerfile was doing some unusual things (both building liftbridge from source using go get and copying the pre-build binary from filesystem). Have reduced this to just building using go get. I updated the version of go in the Dockerfile too, to match what's in go.mod
=> Remove unused Dockerfile directives

server/api.go
Noticed this small mistake while trying liftbridge out locally:
```
msg="api: FetchPartitionMetadata [stream=%s, partition=%s]test0"
```
=> Correct FetchPartitionMetadata debug log

server/activity.go, server/api.go, server/cursors.go, server/server.go, server/server_test.go
Fix #283 where server can become metadata leader before a loopback
client has been created. This replaces the loopback client with direct
API calls.
=> Fix loopback client race

docker/dev-standalone/liftbridge.yaml
Use 0.0.0.0 as the default rather than localhost so that clients can
connect by default.
This fixes https://github.com/liftbridge-io/go-liftbridge/issues/94.
=> Change dev-standalone host default to 0.0.0.0

docker/dev-standalone/Dockerfile
Realised I introduced a bug with #281 
Go get by default fetches the latest tagged version (v1.3.0), whereas here we want the tip of master.
I think we'll always want to fetch master in the current build pipeline, but I could set this up as a docker build arg if it wants to be variable?
=> Get master for dev-standalone docker image

documentation/configuration.md, go.mod, go.sum, server/api.go, server/api_test.go, server/config.go, server/config_test.go, server/configs/full.yaml, server/metadata.go, server/partition.go, server/raft.go, server/replicator.go, website/i18n/en.json
Add a configuration for setting the max replication size so that users
can adjust it based on the configured NATS max_payload size. Also reject
publishes that exceed this limit.
Fixes #305
=> Add clustering.replication.max.bytes config

documentation/configuration.md, documentation/embedded_nats.md, documentation/quick_start.md, documentation/roadmap.md, go.mod, go.sum, main.go, server/config.go, server/config_test.go, server/configs/full.yaml, server/logger/logger.go, server/server.go, server/version.go, website/i18n/en.json, website/sidebars.json
Add support for running an embedded NATS server in the Liftbridge process with new `nats.embedded` and `nats.embedded.config` settings (and flags).
Resolves #19.
=> Embedded NATS

documentation/replication_protocol.md, server/metadata.go, server/metadata_test.go
Change the selection of partition replicas and leaders from being
random to selecting based on least load. This provides better
distribution of partition load across servers in the cluster.
=> Change partition replicas and leader selection

server/raft.go, server/server.go
Also add some logging around Raft initialization and panic when the Raft
node is unexpectedly nil.
Fix #322
=> Fix race with Raft node initialization

server/commitlog/commitlog.go, server/commitlog/segment.go, server/commitlog/segment_test.go, server/metadata.go, website/i18n/en.json
Fix an issue where the replication waiter logic which occurs when a
follower is caught up with the leader causes a flood of notify and
replication requests.
This fixes issue #313.
Also fix an edge case deadlock issue when there is a leader change for a
partition but there is no metadata leader.
=> Fix replication notify flood leading to high CPU usage

server/fsm.go, server/server.go, server/server_test.go
This PR adds a listener for Raft log entries to the `Server`.
Fixes https://github.com/liftbridge-io/liftbridge/issues/335.
=> Add a Raft log listener

server/partition.go
Fix a bug which made it possible for the HW to move backwards in the
event of a leader failover. Fixes #319.
=> Fix possibility for HW to move backwards

server/replicator_test.go
Addressing https://github.com/liftbridge-io/liftbridge/issues/311
Changes:
- In each test, make sure not to kill the server that is serving the test client
- If we have to kill the partition's leader in the test, then reconnect the client
=> Fix flaky replication test

server/commitlog/commitlog.go, server/commitlog/commitlog_test.go
Fix EOF error that occurs when using StartAtTime to subscribe to a
partition that is empty or otherwise has a timestamp that is beyond the
end of the log.
Fixes #323
=> Fix StartAtTime EOF error

go.mod, go.sum, server/api_test.go, server/metadata.go
Required: https://github.com/liftbridge-io/liftbridge-api/pull/53
To solve: https://github.com/liftbridge-io/liftbridge/issues/274
This would enable the server to provide information about work loads on `FetchMetadata` endpoint, thus allow the client to better decide to which server it should connect to.
=> Expose information about server's loads on FetchMetadata

server/fsm.go, server/server.go
Fix a race condition related to the mutex guarding raftLogListeners by
replacing it with a finer-grained mutex.
=> Fix race with raftLogListeners mutex

server/activity.go, server/api.go, server/api_test.go, server/metadata.go, server/server.go, server/stream.go
Previously the `cursors.stream.auto.pause.time` configuration could not be changed once the cursors stream was created. This allows it to be changed in the configuration file and take effect upon server restart.
This is related to the discussion in https://github.com/liftbridge-io/liftbridge/issues/390.
This also prevents clients from creating or deleting "reserved" streams, i.e. `__cursors` and `__activity`.
=> Allow cursors.stream.auto.pause.time to be changed

server/cursors.go, server/partition.go
Clear the cursor cache when a server becomes the leader for a cursor
partition to avoid the potential for serving stale cursors.
Fixes #319
=> Fix potential for serving stale cursors

server/metadata.go
Use a default timeout for fetching broker info that is separate from the
default propagate timeout.
=> Default fetch broker info timeout to 3 seconds

server/metadata.go, server/partition.go, server/partition_test.go, server/raft.go, server/replicator.go, server/replicator_test.go, server/server.go, server/server_test.go, server/signal.go
Also resolve some race conditions related to server shutdown which was causing tests to deadlock on occasion.
=> Fix flaky tests and race conditions

server/partition.go
We don't need to panic when there is an error adding to the commit queue
since Liftbridge's replication protocol will handle uncommitted
messages.
=> Fix panic caused by partition queue dispose

main.go
Remove the override logic for the tls-client-* flags since these flags
were never exposed.
=> Remove override logic for tls-client-* flags
